import { Badge, Flex } from "@mantine/core";
import React from "react";

export default function GenerativeAIBadge() {
  return (
    <Flex>
      <Badge variant="filled" color="blue" radius="md">Generated By AI</Badge>
    </Flex>
  );
}
