import { Badge } from "@mantine/core";
import React from "react";

export default function GenerativeAIBadge() {
  return (
    <div>
      <Badge variant="filled" color="blue" radius="md">Generated By AI</Badge>
    </div>
  );
}
